AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template for vpc and subnet setup'
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: us-east-1a
  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: us-east-1b

Outputs:
  VpcId:
    Value: !Ref VPC
    Export:
      Name: VpcId
  Subnet1Id:
    Value: !Ref Subnet1
    Export:
      Name: Subnet1Id
  Subnet2Id:
    Value: !Ref Subnet2
    Export:
      Name: Subnet2Id
